version: "3"

services:

  flask:
    build:
      context: ./flask/
    ports:
      - "8000:8000"
  fastapi:
    build:
      context: ./fastapi/
    ports:
      - "5000:5000"
  blacksheep:
    build:
      context: ./blacksheep/
    ports:
      - "5050:5050"
  wrk:
    image: xiaopeng163/net-box:latest
    command: /bin/sh -c "while true; do sleep 3600; done"
